### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/timesheet#1]
## The todo list.

- [ ] Consolidate repeated version references
- [ ] Implement the `outfile` option.
- [ ] Make the issue regex case insensitive.
- [ ] Finish implementing the `verbose` flag.
- [ ] Finish implementing the `dryrun` flag.
- [ ] Add a `startdate` option to bound the output.
